#![allow(ambiguous_glob_reexports)]

pub mod add_beneficiary;
pub mod add_guardian;
pub mod claim;
pub mod claim_spl;
pub mod close_vault;
pub mod create_vault;
pub mod deposit;
pub mod deposit_spl;
pub mod dispute;
pub mod guardian_heartbeat;
pub mod heartbeat;
pub mod lock_vault;
pub mod trigger_countdown;

// Glob re-exports are required so that Anchor's #[program] macro can resolve
// the internal __client_accounts_* types generated by #[derive(Accounts)].
pub use add_beneficiary::*;
pub use add_guardian::*;
pub use claim::*;
pub use claim_spl::*;
pub use close_vault::*;
pub use create_vault::*;
pub use deposit::*;
pub use deposit_spl::*;
pub use dispute::*;
pub use guardian_heartbeat::*;
pub use heartbeat::*;
pub use lock_vault::*;
pub use trigger_countdown::*;
